import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "./providers";
import PathNameNavbar from "@/PathnameLayout/pathnameNavbar";
import PathNameFooter from "@/PathnameLayout/pathnameFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <PathNameNavbar />
          {children}
          <PathNameFooter />
        </AuthProvider>
      </body>
    </html>
  );
}
